"""Pre-train a MaskablePPO policy via behavioral cloning on MaxDamagePlayer data.

Loads the dataset generated by generate_bc_data.py and trains the policy
network to imitate MaxDamagePlayer's move selection via supervised learning
(masked cross-entropy loss over legal actions only).

The resulting model serves as a warm-start for RL training — the agent
begins with "pick the highest-damage move" as a baseline skill instead
of starting from random.

Usage:
    python scripts/behavioral_cloning.py                    # default
    python scripts/behavioral_cloning.py --epochs 100       # more epochs
    python scripts/behavioral_cloning.py --data path.npz    # custom data
"""

import argparse
import os
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from sb3_contrib import MaskablePPO
from stable_baselines3.common.vec_env import DummyVecEnv

_ROOT = Path(__file__).parent.parent
os.chdir(_ROOT)
sys.path.insert(0, str(_ROOT))

from src.env.gen1_env import make_env

# Must match train.py PPO_KWARGS
OBS_DIM = 1739
ACTION_DIM = 10


def load_data(path: str, val_split: float = 0.1):
    """Load and split BC training data."""
    data = np.load(path)
    obs = data["observations"].astype(np.float32)
    actions = data["actions"].astype(np.int64)
    masks = data["masks"].astype(np.float32)

    n = len(obs)
    indices = np.random.permutation(n)
    split = int(n * (1 - val_split))

    train_idx, val_idx = indices[:split], indices[split:]
    return (
        (obs[train_idx], actions[train_idx], masks[train_idx]),
        (obs[val_idx], actions[val_idx], masks[val_idx]),
    )


def masked_cross_entropy(logits: torch.Tensor, actions: torch.Tensor, masks: torch.Tensor) -> torch.Tensor:
    """Cross-entropy loss computed only over legal actions.

    Illegal actions are masked to -inf before softmax so they get zero
    probability and don't contribute to the loss.
    """
    # Mask illegal actions to -inf
    masked_logits = logits + (masks.log())  # log(0) = -inf for illegal, log(1) = 0 for legal
    return F.cross_entropy(masked_logits, actions)


def compute_accuracy(logits: torch.Tensor, actions: torch.Tensor, masks: torch.Tensor) -> float:
    """Accuracy of predicted action (highest logit among legal actions)."""
    masked_logits = logits.clone()
    masked_logits[masks == 0] = -float("inf")
    preds = masked_logits.argmax(dim=1)
    return (preds == actions).float().mean().item()


def train_bc(
    data_path: str,
    output_path: str,
    epochs: int = 50,
    batch_size: int = 256,
    lr: float = 1e-3,
    policy_kwargs: dict | None = None,
):
    """Train behavioral cloning model."""
    print(f"Loading data from {data_path}...")
    (train_obs, train_act, train_mask), (val_obs, val_act, val_mask) = load_data(data_path)
    print(f"  Train: {len(train_obs)} transitions")
    print(f"  Val:   {len(val_obs)} transitions")

    obs_dim = train_obs.shape[1]
    print(f"  Obs dim: {obs_dim}")

    # Create a dummy env just to initialize MaskablePPO with correct spaces
    from functools import partial

    env = DummyVecEnv([partial(make_env, env_index=0, battle_format="gen1randombattle")])

    ppo_kwargs = dict(
        policy="MlpPolicy",
        env=env,
        n_steps=2048,
        batch_size=64,
        learning_rate=lr,
        gamma=0.99,
        gae_lambda=0.95,
        clip_range=0.2,
        ent_coef=0.01,
        verbose=0,
    )
    if policy_kwargs:
        ppo_kwargs["policy_kwargs"] = policy_kwargs

    model = MaskablePPO(**ppo_kwargs)
    policy = model.policy
    device = policy.device

    # Convert data to tensors
    t_obs = torch.tensor(train_obs, device=device)
    t_act = torch.tensor(train_act, device=device)
    t_mask = torch.tensor(train_mask, device=device)
    v_obs = torch.tensor(val_obs, device=device)
    v_act = torch.tensor(val_act, device=device)
    v_mask = torch.tensor(val_mask, device=device)

    # Optimizer for the policy network only (not value function)
    optimizer = torch.optim.Adam(policy.parameters(), lr=lr)
    n_batches = max(1, (len(t_obs) + batch_size - 1) // batch_size)  # ceil division, include tail

    print(f"\nTraining for {epochs} epochs, {n_batches} batches/epoch, lr={lr}")
    print(f"{'Epoch':>5} | {'Train Loss':>10} | {'Train Acc':>9} | {'Val Loss':>10} | {'Val Acc':>9}")
    print("-" * 55)

    best_val_acc = 0.0

    for epoch in range(epochs):
        # Shuffle indices instead of copying full tensors (saves GPU memory)
        perm = torch.randperm(len(t_obs), device=device)

        policy.train()
        epoch_loss = 0.0
        epoch_acc = 0.0
        batches_processed = 0

        for i in range(n_batches):
            start = i * batch_size
            end = min(start + batch_size, len(t_obs))
            idx = perm[start:end]
            b_obs = t_obs[idx]
            b_act = t_act[idx]
            b_mask = t_mask[idx]

            # Forward pass through the policy's action network
            features = policy.extract_features(b_obs, policy.pi_features_extractor)
            latent_pi = policy.mlp_extractor.forward_actor(features)
            logits = policy.action_net(latent_pi)

            loss = masked_cross_entropy(logits, b_act, b_mask)
            acc = compute_accuracy(logits, b_act, b_mask)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            epoch_acc += acc
            batches_processed += 1

        epoch_loss /= max(batches_processed, 1)
        epoch_acc /= max(batches_processed, 1)

        # Validation
        policy.eval()
        with torch.no_grad():
            features = policy.extract_features(v_obs, policy.pi_features_extractor)
            latent_pi = policy.mlp_extractor.forward_actor(features)
            logits = policy.action_net(latent_pi)
            val_loss = masked_cross_entropy(logits, v_act, v_mask).item()
            val_acc = compute_accuracy(logits, v_act, v_mask)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            marker = " *"
        else:
            marker = ""

        if (epoch + 1) % 5 == 0 or epoch == 0 or marker:
            print(
                f"{epoch + 1:>5} | {epoch_loss:>10.4f} | {epoch_acc:>8.1%} | {val_loss:>10.4f} | {val_acc:>8.1%}{marker}"
            )

    print(f"\nBest validation accuracy: {best_val_acc:.1%}")

    # Copy BC-trained actor features to initialize the value function.
    # policy_net and value_net have identical architecture [256, 128],
    # so weights can be copied directly. This gives the value function
    # useful feature representations instead of random initialization.
    with torch.no_grad():
        pi_params = list(model.policy.mlp_extractor.policy_net.parameters())
        vf_params = list(model.policy.mlp_extractor.value_net.parameters())
        for pi_p, vf_p in zip(pi_params, vf_params, strict=False):
            vf_p.data.copy_(pi_p.data)
        copied = sum(p.numel() for p in vf_params)
        print(f"Copied policy_net weights to value_net ({copied:,} params)")

    # Save the full MaskablePPO model (policy + value function)
    os.makedirs(Path(output_path).parent, exist_ok=True)
    model.save(output_path)
    print(f"Saved to {output_path}.zip")

    # Cleanup the dummy env
    env.close()

    return best_val_acc


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default="data/bc_training_data.npz")
    parser.add_argument("--output", default="models/bc_warmstart")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=1e-3)
    args = parser.parse_args()

    train_bc(
        data_path=args.data,
        output_path=args.output,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        policy_kwargs=dict(net_arch=dict(pi=[256, 128], vf=[256, 128])),
    )


if __name__ == "__main__":
    main()
